### ISSUE TITLE
Circular handlers 

### ISSUE THREAD

**Issue by leepike** [GaloisInc/ivory-tower-stm32#4]
Ok, I tracked down the circular handler issue in the I2C driver, but I'm not quite sure how to fix it. The offending channel is from the one sent from [request handler](https://github.com/GaloisInc/ivory-tower-stm32/blob/master/ivory-bsp-stm32/src/Ivory/BSP/STM32/Driver/I2C.hs#L412) on error. This is because the scheduler's response handler emits to the driver's request handler, causing a circularity.

(Note that, for example, the SPI driver only emits to the scheduler's response handler from the IRQ handler, not the response handler.)

I don't know enough the details to suggest a change, but we only emit in the invalid branch, perhaps it is enough to just log the invalid request?

**Comment by acfoltzer** [comment]
Good catch. The trick here is that in order for the scheduler to not get stuck, there needs to be a 1-1 correspondence between requests and responses. I think the right thing to do here is to post a flag in the request handler, then have a watchdog thread send an error response if it's set. That should break the circularity, but is kind of ugly.

This is the sort of thing where I wish the scheduler interface more gracefully admitted the possibility of errors. Although even if it did have a separate handler for the error case, there would be a cycle if that handler immediately tried to reschedule the next task.

**Comment by acfoltzer** [comment]
I'm gonna close this once I merge the changes into `master` along with the px4flow driver and new alt estimator.
